package com.ragkb.service.modules.governance.persistence.entity;

import com.ragkb.service.common.persistence.BaseAuditEntity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.Instant;


/**
 * {@code deletion_task} 表实体 —— MyBatis-Plus 骨架（对齐 {@code deploy/ddl/init.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>⚠️ 骨架：JSONB 列当前映射为 {@code String}，业务实现时切换
 * {@code @TableField(typeHandler = JacksonTypeHandler.class)} +
 * {@code @TableName(autoResultMap = true)}；insert 时 null 字段不落 SQL，
 * 由数据库默认值（now() 等）填充。本类不含业务逻辑。
 */
@TableName("deletion_task")
public class DeletionTask extends BaseAuditEntity {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long tenantId;

    private String resourceType;

    private String resourceId;

    private String reason;

    private Long requestedBy;

    private String idempotencyKey;

    private String status;

    private String previewJson;

    private Boolean legalHoldBlocked;

    private String blockedReasonCode;

    private Integer targetCount;

    private Integer completedCount;

    private Integer failedCount;

    private Instant startedAt;

    private Instant completedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceId() {
        return resourceId;
    }

    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Long getRequestedBy() {
        return requestedBy;
    }

    public void setRequestedBy(Long requestedBy) {
        this.requestedBy = requestedBy;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getPreviewJson() {
        return previewJson;
    }

    public void setPreviewJson(String previewJson) {
        this.previewJson = previewJson;
    }

    public Boolean getLegalHoldBlocked() {
        return legalHoldBlocked;
    }

    public void setLegalHoldBlocked(Boolean legalHoldBlocked) {
        this.legalHoldBlocked = legalHoldBlocked;
    }

    public String getBlockedReasonCode() {
        return blockedReasonCode;
    }

    public void setBlockedReasonCode(String blockedReasonCode) {
        this.blockedReasonCode = blockedReasonCode;
    }

    public Integer getTargetCount() {
        return targetCount;
    }

    public void setTargetCount(Integer targetCount) {
        this.targetCount = targetCount;
    }

    public Integer getCompletedCount() {
        return completedCount;
    }

    public void setCompletedCount(Integer completedCount) {
        this.completedCount = completedCount;
    }

    public Integer getFailedCount() {
        return failedCount;
    }

    public void setFailedCount(Integer failedCount) {
        this.failedCount = failedCount;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(Instant startedAt) {
        this.startedAt = startedAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(Instant completedAt) {
        this.completedAt = completedAt;
    }
}
