package com.ragkb.service.modules.analytics.persistence.entity;

import com.ragkb.service.common.persistence.BaseAuditEntity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;


/**
 * {@code usage_daily} 表实体 —— MyBatis-Plus 骨架（对齐 {@code deploy/ddl/init.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>⚠️ 骨架：JSONB 列当前映射为 {@code String}，业务实现时切换
 * {@code @TableField(typeHandler = JacksonTypeHandler.class)} +
 * {@code @TableName(autoResultMap = true)}；insert 时 null 字段不落 SQL，
 * 由数据库默认值（now() 等）填充。本类不含业务逻辑。
 */
@TableName("usage_daily")
public class UsageDaily extends BaseAuditEntity {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long tenantId;

    private Long kbId;

    private LocalDate statDate;

    private Long searchCount;

    private Long qaCount;

    private Long noAnswerCount;

    private Long lowConfCount;

    private Long tokenIn;

    private Long tokenOut;

    private Integer activeUsers;

    private BigDecimal cost;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getKbId() {
        return kbId;
    }

    public void setKbId(Long kbId) {
        this.kbId = kbId;
    }

    public LocalDate getStatDate() {
        return statDate;
    }

    public void setStatDate(LocalDate statDate) {
        this.statDate = statDate;
    }

    public Long getSearchCount() {
        return searchCount;
    }

    public void setSearchCount(Long searchCount) {
        this.searchCount = searchCount;
    }

    public Long getQaCount() {
        return qaCount;
    }

    public void setQaCount(Long qaCount) {
        this.qaCount = qaCount;
    }

    public Long getNoAnswerCount() {
        return noAnswerCount;
    }

    public void setNoAnswerCount(Long noAnswerCount) {
        this.noAnswerCount = noAnswerCount;
    }

    public Long getLowConfCount() {
        return lowConfCount;
    }

    public void setLowConfCount(Long lowConfCount) {
        this.lowConfCount = lowConfCount;
    }

    public Long getTokenIn() {
        return tokenIn;
    }

    public void setTokenIn(Long tokenIn) {
        this.tokenIn = tokenIn;
    }

    public Long getTokenOut() {
        return tokenOut;
    }

    public void setTokenOut(Long tokenOut) {
        this.tokenOut = tokenOut;
    }

    public Integer getActiveUsers() {
        return activeUsers;
    }

    public void setActiveUsers(Integer activeUsers) {
        this.activeUsers = activeUsers;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

}
