package com.ragkb.service.modules.identity.persistence.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.Instant;
import java.io.Serializable;

/**
 * {@code identity_account} 表实体 —— MyBatis-Plus 骨架（对齐 {@code deploy/ddl/init.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>⚠️ 骨架：JSONB 列当前映射为 {@code String}，业务实现时切换
 * {@code @TableField(typeHandler = JacksonTypeHandler.class)} +
 * {@code @TableName(autoResultMap = true)}；insert 时 null 字段不落 SQL，
 * 由数据库默认值（now() 等）填充。本类不含业务逻辑。
 */
@TableName("identity_account")
public class IdentityAccount implements Serializable {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long userId;

    private String protocol;

    private String issuer;

    private String subject;

    private String emailAtLink;

    private Instant lastLoginAt;

    private Instant createdAt;

    private Instant updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getIssuer() {
        return issuer;
    }

    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getEmailAtLink() {
        return emailAtLink;
    }

    public void setEmailAtLink(String emailAtLink) {
        this.emailAtLink = emailAtLink;
    }

    public Instant getLastLoginAt() {
        return lastLoginAt;
    }

    public void setLastLoginAt(Instant lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
