package com.ragkb.service.modules.identity.persistence.entity;

import com.ragkb.service.common.persistence.BaseAuditEntity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.Version;
import java.time.Instant;


/**
 * {@code tenant_member} 表实体 —— MyBatis-Plus 骨架（对齐 {@code deploy/ddl/init.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>⚠️ 骨架：JSONB 列当前映射为 {@code String}，业务实现时切换
 * {@code @TableField(typeHandler = JacksonTypeHandler.class)} +
 * {@code @TableName(autoResultMap = true)}；insert 时 null 字段不落 SQL，
 * 由数据库默认值（now() 等）填充。本类不含业务逻辑。
 */
@TableName("tenant_member")
public class TenantMember extends BaseAuditEntity {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long tenantId;

    private Long userId;

    private String status;

    private Instant joinedAt;

    private Instant suspendedAt;

    @Version
    private Long rowVersion;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Instant getJoinedAt() {
        return joinedAt;
    }

    public void setJoinedAt(Instant joinedAt) {
        this.joinedAt = joinedAt;
    }

    public Instant getSuspendedAt() {
        return suspendedAt;
    }

    public void setSuspendedAt(Instant suspendedAt) {
        this.suspendedAt = suspendedAt;
    }

    public Long getRowVersion() {
        return rowVersion;
    }

    public void setRowVersion(Long rowVersion) {
        this.rowVersion = rowVersion;
    }
}
