package com.ragkb.service.modules.identity.persistence.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.Instant;
import java.io.Serializable;

/**
 * {@code tenant_member_role} 表实体 —— MyBatis-Plus 骨架（对齐 {@code deploy/ddl/init.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>⚠️ 骨架：JSONB 列当前映射为 {@code String}，业务实现时切换
 * {@code @TableField(typeHandler = JacksonTypeHandler.class)} +
 * {@code @TableName(autoResultMap = true)}；insert 时 null 字段不落 SQL，
 * 由数据库默认值（now() 等）填充。本类不含业务逻辑。
 */
@TableName("tenant_member_role")
public class TenantMemberRole implements Serializable {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long tenantId;

    private Long userId;

    private String role;

    private Instant createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
