package com.ragkb.service.modules.identity.persistence.entity;

import com.ragkb.service.common.persistence.BaseAuditEntity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.Version;
import java.time.Instant;


/**
 * {@code user_credential} 表实体 —— 本地账号登录凭据（对齐 {@code deploy/ddl/migrations/V0.4__local_user_credentials.sql}）。
 *
 * <p>约定：主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}；
 * {@code row_version} 乐观锁 → {@link Version}；snake_case 列自动映射 camelCase 属性
 * （map-underscore-to-camel-case）；时间戳用 {@link Instant}。
 *
 * <p>语义：本表只存登录标识 + BCrypt hash + 凭据策略（失败计数/锁定/过期）；
 * {@code sys_user} 仍是全局身份唯一真相（display_name/email/status），不在此重复。
 * 登录标识按 {@code lower(username)} 全局唯一（见 DDL 唯一索引）。
 *
 * <p>⚠️ 本类不含业务逻辑。凭据策略（状态门禁/过期判定/失败锁定）由
 * {@code JdbcUserDetailsService} / {@code JdbcUserCredentialStore} 实现（谨慎区，人工复核）。
 */
@TableName("user_credential")
public class UserCredential extends BaseAuditEntity {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long userId;

    private String username;

    private String passwordHash;

    /** ACTIVE / DISABLED / LOCKED（对齐 DDL CHECK）。 */
    private String status;

    private Integer failedAttempts;

    private Instant lockedUntil;

    private Instant passwordChangedAt;

    private Instant passwordExpiresAt;

    /** true=下次成功登录后必须先改密才能使用系统（createLocalUser / 管理员重置置 true，改密成功置 false）。 */
    private Boolean mustChangePassword;

    @Version
    private Long rowVersion;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getFailedAttempts() {
        return failedAttempts;
    }

    public void setFailedAttempts(Integer failedAttempts) {
        this.failedAttempts = failedAttempts;
    }

    public Instant getLockedUntil() {
        return lockedUntil;
    }

    public void setLockedUntil(Instant lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    public Instant getPasswordChangedAt() {
        return passwordChangedAt;
    }

    public void setPasswordChangedAt(Instant passwordChangedAt) {
        this.passwordChangedAt = passwordChangedAt;
    }

    public Instant getPasswordExpiresAt() {
        return passwordExpiresAt;
    }

    public void setPasswordExpiresAt(Instant passwordExpiresAt) {
        this.passwordExpiresAt = passwordExpiresAt;
    }

    public Boolean getMustChangePassword() {
        return mustChangePassword;
    }

    public void setMustChangePassword(Boolean mustChangePassword) {
        this.mustChangePassword = mustChangePassword;
    }

    public Long getRowVersion() {
        return rowVersion;
    }

    public void setRowVersion(Long rowVersion) {
        this.rowVersion = rowVersion;
    }
}
