-- =====================================================================
-- v0.4 · 本地账号凭据表 user_credential（form 登录落库）
-- 目标：PostgreSQL 16+，在 v0.3 基线之上执行；逐语句幂等（重跑安全），执行前建议备份。
--
-- 背景：form 账号密码登录的用户此前来自内存配置（ragkb.auth.dev.*），不落库。
-- 本迁移建立 user_credential 表，让"谁能登录"由数据库决定：
--   * sys_user 仍是全局身份唯一真相（不保存密码的 COMMENT 不变）；
--   * user_credential 只存登录标识 + BCrypt hash + 凭据策略（失败计数/锁定/过期）；
--   * 同步 seed bootstrap 管理员（对齐 init.sql 的默认租户 id=1）。
-- 关联代码：UserCredential / UserCredentialMapper / UserCredentialStorePort /
--           JdbcUserDetailsService / JdbcIdentityDirectory（service 模块 identity）。
--
-- 说明：
--   * 触发器依赖 v0.3 建立的 set_update_time() 函数；若函数不存在则跳过触发器（幂等不报错）。
--   * 回滚：不提供自动 down；如需回退，按 docs/04 §9.3 由 DBA 评审执行。
-- =====================================================================

-- 执行方式：纯 SQL（不含 psql 元命令），兼容 psql / DBeaver / IDE / JDBC / 迁移工具。
--   psql -v ON_ERROR_STOP=1 -f deploy/ddl/migrations/V0.4__local_user_credentials.sql
-- 幂等性：对"已应用"状态逐语句幂等（重跑零报错，全为 no-op）：
--   * CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS
--   * INSERT ... ON CONFLICT ... DO NOTHING（sys_user 按 id、user_credential 按 lower(username)
--     约束、tenant_member 按 (tenant_id,user_id)、tenant_member_role 按 (tenant_id,user_id,role)）
--   * 触发器先 DROP IF EXISTS 再 CREATE，且在 set_update_time() 不存在时跳过
--   * SELECT setval 固定到当前 max(id)，重跑无副作用
-- 注意：本迁移按"连接角色"直接执行，内部不再 SET ROLE 切换角色。
--   DDL 需要表属主（或其成员）或超级用户权限：
--   推荐以 ragkb_migrator 连接执行（ragkb_owner 成员，专门跑迁移）；postgres 超级用户亦可。
--   ragkb_app 是运行时 DML 角色，无 DDL 权限，用它执行会报 must be owner of table ...。
BEGIN;

-- ---------------------------------------------------------------------
-- 1. 建表 user_credential
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_credential (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL REFERENCES sys_user(id),
    username            VARCHAR(254) NOT NULL,
    password_hash       VARCHAR(100) NOT NULL,               -- BCrypt（通常 60 字符）
    status              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    failed_attempts     INTEGER      NOT NULL DEFAULT 0,
    locked_until        TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    password_expires_at TIMESTAMPTZ,
    create_time         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    update_time         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    create_by           BIGINT,
    update_by           BIGINT,
    del_flag            SMALLINT     NOT NULL DEFAULT 0,
    row_version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_credential_username UNIQUE (lower(username)),
    CONSTRAINT ck_user_credential_status CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    CONSTRAINT ck_user_credential_attempts CHECK (failed_attempts >= 0),
    CONSTRAINT ck_user_credential_locked CHECK (
        (status = 'LOCKED' AND locked_until IS NOT NULL)
        OR (status <> 'LOCKED' AND locked_until IS NULL)
    )
);

-- 登录标识按 lower(username) 全局唯一（form|username subjectKey 本身是全局的）
CREATE INDEX IF NOT EXISTS idx_user_credential_user ON user_credential (user_id);

COMMENT ON TABLE user_credential IS
'本地账号登录凭据：仅存 BCrypt hash 与登录标识/凭据策略；sys_user 仍是全局身份唯一真相，本表不重复身份属性';

-- 触发器维护 update_time（依赖 v0.3 的 set_update_time()；不存在则跳过，保证幂等）
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = current_schema() AND p.proname = 'set_update_time'
    ) THEN
        DROP TRIGGER IF EXISTS trg_user_credential_update_time ON user_credential;
        CREATE TRIGGER trg_user_credential_update_time BEFORE UPDATE ON user_credential
            FOR EACH ROW EXECUTE FUNCTION set_update_time();
    END IF;
END
$$;

-- ---------------------------------------------------------------------
-- 2. bootstrap 管理员（幂等 seed；对齐 init.sql 默认租户 id=1 / code='default'）
--
-- ⚠️ 安全提示：seed 口令 admin123 仅供本地/私有化开箱即用，且哈希已入库，
--    生产部署前必须重新生成 BCrypt hash 替换（htpasswd -bnBC 10 "" '<新口令>' | tr -d ':\n'）
--    并走受审计 SQL 轮换（改密 API 属后续迭代）。纯 oidc 部署不应启用 form 登录。
-- ---------------------------------------------------------------------
INSERT INTO sys_user (id, primary_email, display_name, status, create_time, update_time)
VALUES (1, 'admin@ragkb.dev', 'Bootstrap Admin', 'ACTIVE', now(), now())
ON CONFLICT (id) DO NOTHING;

-- admin123 的 BCrypt hash（$2y$10$...，Spring BCryptPasswordEncoder 兼容）
INSERT INTO user_credential (user_id, username, password_hash, status, password_changed_at)
VALUES (1, 'admin', '$2y$10$mJmjunqPwc0cDJboJoL7cOHpum9CQdcL6/1bJhZpA8oZqFmg2LPd2', 'ACTIVE', now())
ON CONFLICT ON CONSTRAINT uq_user_credential_username DO NOTHING;

INSERT INTO tenant_member (tenant_id, user_id, status, joined_at)
VALUES (1, 1, 'ACTIVE', now())
ON CONFLICT (tenant_id, user_id) DO NOTHING;

INSERT INTO tenant_member_role (tenant_id, user_id, role)
VALUES (1, 1, 'TENANT_ADMIN')
ON CONFLICT (tenant_id, user_id, role) DO NOTHING;

-- 回填自增序列（幂等：固定到当前 max(id)）
SELECT setval(pg_get_serial_sequence('sys_user', 'id'),
    GREATEST((SELECT max(id) FROM sys_user), 1), true);
SELECT setval(pg_get_serial_sequence('user_credential', 'id'),
    GREATEST((SELECT max(id) FROM user_credential), 1), true);
SELECT setval(pg_get_serial_sequence('tenant_member', 'id'),
    GREATEST((SELECT max(id) FROM tenant_member), 1), true);
SELECT setval(pg_get_serial_sequence('tenant_member_role', 'id'),
    GREATEST((SELECT max(id) FROM tenant_member_role), 1), true);

COMMIT;
