package com.ragkb.service.modules.tenant.persistence.entity;

import com.ragkb.service.common.persistence.BaseAuditEntity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.Version;

import java.time.Instant;

/**
 * {@code sys_tenant} 表实体 —— MyBatis-Plus 骨架模板。
 *
 * <p>约定（对齐 {@code deploy/ddl/init.sql}）：
 * <ul>
 *   <li>主键 {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link IdType#AUTO}（数据库生成）；</li>
 *   <li>{@code row_version} 乐观锁 → {@link @Version}（配合 OptimisticLockerInnerInterceptor）；</li>
 *   <li>snake_case 列自动映射 camelCase 属性（map-underscore-to-camel-case）；</li>
 *   <li>时间戳用 {@link Instant}（TIMESTAMPTZ），业务接口 DTO 同约定。</li>
 * </ul>
 *
 * <p>⚠️ 模板：实现其它表时复制本类，改 {@code @TableName} 与字段即可；
 * 不要在本骨架类里加业务逻辑。insert 时 null 字段不落 SQL，由数据库默认值（now() 等）填充。
 */
@TableName("sys_tenant")
public class SysTenant extends BaseAuditEntity {

    @TableId(type = IdType.AUTO)
    private Long id;

    private String code;

    private String name;

    private String deploymentMode;

    private String dataRegion;

    private String status;

    private Long policyVersion;

    @Version
    private Long rowVersion;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDeploymentMode() {
        return deploymentMode;
    }

    public void setDeploymentMode(String deploymentMode) {
        this.deploymentMode = deploymentMode;
    }

    public String getDataRegion() {
        return dataRegion;
    }

    public void setDataRegion(String dataRegion) {
        this.dataRegion = dataRegion;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getPolicyVersion() {
        return policyVersion;
    }

    public void setPolicyVersion(Long policyVersion) {
        this.policyVersion = policyVersion;
    }

    public Long getRowVersion() {
        return rowVersion;
    }

    public void setRowVersion(Long rowVersion) {
        this.rowVersion = rowVersion;
    }
}
