-- =====================================================================
-- 通用企业知识库平台 · PostgreSQL Schema（v0.2，新装基线）
-- 目标：PostgreSQL 16+
-- 权威设计：docs/04-数据库设计.md
--
-- 安全边界：
--   * tenant 资源使用 tenant_id + 复合外键阻止跨租户关联
--   * ragkb_owner 拥有对象；ragkb_app 仅 DML 且无 BYPASSRLS
--   * RLS 在应用设置 tenant context 后由 04-enable-tenant-rls.sql 启用
--   * 原文/密钥不存本 Schema；仅保存 object_key、secret_ref 或不可逆摘要
-- =====================================================================

\set ON_ERROR_STOP on
SET ROLE ragkb_owner;
BEGIN;

CREATE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- 1. Tenant / Identity -------------------------------------------------

CREATE TABLE sys_tenant (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(64)  NOT NULL,
    name             VARCHAR(128) NOT NULL,
    deployment_mode  VARCHAR(16)  NOT NULL DEFAULT 'SAAS',
    data_region      VARCHAR(64)  NOT NULL DEFAULT 'default',
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    policy_version   BIGINT       NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    row_version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_tenant_code UNIQUE (code),
    CONSTRAINT ck_sys_tenant_code CHECK (code ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
    CONSTRAINT ck_sys_tenant_mode CHECK (deployment_mode IN ('SAAS', 'PRIVATE')),
    CONSTRAINT ck_sys_tenant_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETING')),
    CONSTRAINT ck_sys_tenant_policy_version CHECK (policy_version >= 1)
);

CREATE TABLE sys_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_email    VARCHAR(254),
    display_name     VARCHAR(128),
    status           VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    last_login_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT ck_sys_user_status CHECK (status IN ('ACTIVE', 'DISABLED', 'DELETED'))
);
CREATE UNIQUE INDEX uq_sys_user_primary_email
    ON sys_user (lower(primary_email)) WHERE primary_email IS NOT NULL;

CREATE TABLE identity_account (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES sys_user(id),
    protocol         VARCHAR(16)  NOT NULL,
    issuer           VARCHAR(512) NOT NULL,
    subject          VARCHAR(512) NOT NULL,
    email_at_link    VARCHAR(254),
    last_login_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_identity_issuer_subject UNIQUE (issuer, subject),
    CONSTRAINT ck_identity_protocol CHECK (protocol IN ('OIDC', 'SAML'))
);
CREATE INDEX idx_identity_account_user ON identity_account (user_id);

CREATE TABLE identity_provider (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    provider_key     VARCHAR(64)  NOT NULL,
    protocol         VARCHAR(16)  NOT NULL,
    issuer           VARCHAR(512),
    discovery_uri    VARCHAR(1024),
    client_id        VARCHAR(256),
    secret_ref       VARCHAR(512),
    scopes           JSONB        NOT NULL DEFAULT '["openid","profile","email"]'::jsonb,
    config           JSONB        NOT NULL DEFAULT '{}'::jsonb,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    row_version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_identity_provider UNIQUE (tenant_id, provider_key),
    CONSTRAINT uq_identity_provider_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT ck_identity_provider_protocol CHECK (protocol IN ('OIDC', 'SAML')),
    CONSTRAINT ck_identity_provider_status CHECK (status IN ('ACTIVE', 'DISABLED', 'ERROR')),
    CONSTRAINT ck_identity_provider_scopes CHECK (jsonb_typeof(scopes) = 'array'),
    CONSTRAINT ck_identity_provider_config CHECK (jsonb_typeof(config) = 'object')
);

CREATE TABLE tenant_member (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    user_id          BIGINT      NOT NULL REFERENCES sys_user(id),
    status           VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    joined_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    suspended_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_tenant_member_user UNIQUE (tenant_id, user_id),
    CONSTRAINT uq_tenant_member_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT ck_tenant_member_status CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED'))
);
CREATE INDEX idx_tenant_member_user ON tenant_member (user_id, status);

CREATE TABLE tenant_member_role (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    user_id          BIGINT      NOT NULL,
    role             VARCHAR(32) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_tenant_member_role_member
        FOREIGN KEY (tenant_id, user_id)
        REFERENCES tenant_member (tenant_id, user_id) ON DELETE CASCADE,
    CONSTRAINT uq_tenant_member_role UNIQUE (tenant_id, user_id, role),
    CONSTRAINT ck_tenant_member_role CHECK (
        role IN ('TENANT_ADMIN', 'SECURITY_ADMIN', 'KNOWLEDGE_ADMIN', 'AUDITOR', 'MEMBER')
    )
);

CREATE TABLE sys_org (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    parent_id        BIGINT,
    external_id      VARCHAR(256),
    name             VARCHAR(128) NOT NULL,
    path             VARCHAR(2048) NOT NULL DEFAULT '/',
    source           VARCHAR(32)  NOT NULL DEFAULT 'LOCAL',
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    row_version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_sys_org_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_sys_org_sibling_name UNIQUE NULLS NOT DISTINCT (tenant_id, parent_id, name),
    CONSTRAINT fk_sys_org_parent
        FOREIGN KEY (tenant_id, parent_id)
        REFERENCES sys_org (tenant_id, id),
    CONSTRAINT ck_sys_org_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_sys_org_path CHECK (path LIKE '/%')
);
CREATE INDEX idx_sys_org_parent ON sys_org (tenant_id, parent_id, sort_order);
CREATE INDEX idx_sys_org_path ON sys_org (tenant_id, path text_pattern_ops);
CREATE UNIQUE INDEX uq_sys_org_external
    ON sys_org (tenant_id, source, external_id) WHERE external_id IS NOT NULL;

CREATE TABLE sys_user_org (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    user_id          BIGINT      NOT NULL,
    org_id           BIGINT      NOT NULL,
    source           VARCHAR(32) NOT NULL DEFAULT 'LOCAL',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sys_user_org_member
        FOREIGN KEY (tenant_id, user_id)
        REFERENCES tenant_member (tenant_id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_org_org
        FOREIGN KEY (tenant_id, org_id)
        REFERENCES sys_org (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_sys_user_org UNIQUE (tenant_id, user_id, org_id)
);
CREATE INDEX idx_sys_user_org_org ON sys_user_org (tenant_id, org_id, user_id);

-- 2. Knowledge configuration -----------------------------------------

CREATE TABLE retention_policy (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    name             VARCHAR(128) NOT NULL,
    scope_type       VARCHAR(24)  NOT NULL,
    scope_key        VARCHAR(128),
    retention_days   INTEGER      NOT NULL,
    disposition      VARCHAR(16)  NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    row_version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_retention_policy_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_retention_policy_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_retention_scope CHECK (scope_type IN ('TENANT', 'KB', 'CLASSIFICATION')),
    CONSTRAINT ck_retention_days CHECK (retention_days > 0),
    CONSTRAINT ck_retention_disposition CHECK (disposition IN ('ARCHIVE', 'DELETE', 'REVIEW')),
    CONSTRAINT ck_retention_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE index_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       NOT NULL REFERENCES sys_tenant(id),
    name                  VARCHAR(128) NOT NULL,
    profile_version       INTEGER      NOT NULL,
    embedding_provider    VARCHAR(128) NOT NULL,
    embedding_model       VARCHAR(256) NOT NULL,
    model_revision        VARCHAR(256) NOT NULL,
    embedding_dimension   INTEGER      NOT NULL,
    normalization         VARCHAR(16)  NOT NULL DEFAULT 'L2',
    distance_metric       VARCHAR(16)  NOT NULL DEFAULT 'COSINE',
    chunker_config        JSONB        NOT NULL,
    analyzer_config       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    reranker_provider     VARCHAR(128),
    reranker_model        VARCHAR(256),
    status                VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    activated_at          TIMESTAMPTZ,
    retired_at            TIMESTAMPTZ,
    CONSTRAINT uq_index_profile_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_index_profile_version UNIQUE (tenant_id, name, profile_version),
    CONSTRAINT ck_index_profile_version CHECK (profile_version >= 1),
    CONSTRAINT ck_index_dimension CHECK (embedding_dimension BETWEEN 64 AND 65536),
    CONSTRAINT ck_index_normalization CHECK (normalization IN ('NONE', 'L2')),
    CONSTRAINT ck_index_metric CHECK (distance_metric IN ('COSINE', 'L2', 'INNER_PRODUCT')),
    CONSTRAINT ck_index_profile_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_index_chunker_json CHECK (jsonb_typeof(chunker_config) = 'object'),
    CONSTRAINT ck_index_analyzer_json CHECK (jsonb_typeof(analyzer_config) = 'object')
);

CREATE TABLE kb (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       NOT NULL REFERENCES sys_tenant(id),
    data_region           VARCHAR(64)  NOT NULL DEFAULT 'default',
    name                  VARCHAR(128) NOT NULL,
    description           VARCHAR(1024),
    visibility            VARCHAR(16)  NOT NULL DEFAULT 'PRIVATE',
    status                VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    index_profile_id      BIGINT       NOT NULL,
    metadata_schema_id    BIGINT,
    retention_policy_id   BIGINT,
    requires_review       BOOLEAN      NOT NULL DEFAULT TRUE,
    ocr_enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    active_index_build_id BIGINT,
    policy_version        BIGINT       NOT NULL DEFAULT 1,
    created_by            BIGINT,
    updated_by            BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ,
    row_version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_kb_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_kb_tenant_name UNIQUE (tenant_id, name),
    CONSTRAINT fk_kb_index_profile
        FOREIGN KEY (tenant_id, index_profile_id)
        REFERENCES index_profile (tenant_id, id),
    CONSTRAINT fk_kb_retention_policy
        FOREIGN KEY (tenant_id, retention_policy_id)
        REFERENCES retention_policy (tenant_id, id),
    CONSTRAINT ck_kb_visibility CHECK (visibility IN ('PRIVATE', 'TENANT')),
    CONSTRAINT ck_kb_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETING', 'DELETED')),
    CONSTRAINT ck_kb_policy_version CHECK (policy_version >= 1),
    CONSTRAINT ck_kb_deleted_at CHECK (
        (status IN ('DELETING', 'DELETED') AND deleted_at IS NOT NULL)
        OR (status NOT IN ('DELETING', 'DELETED') AND deleted_at IS NULL)
    )
);
CREATE INDEX idx_kb_status ON kb (tenant_id, status, updated_at DESC);

CREATE TABLE kb_member (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT      NOT NULL,
    user_id          BIGINT      NOT NULL,
    role             VARCHAR(16) NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_kb_member_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_kb_member_user
        FOREIGN KEY (tenant_id, user_id)
        REFERENCES tenant_member (tenant_id, user_id) ON DELETE CASCADE,
    CONSTRAINT uq_kb_member UNIQUE (tenant_id, kb_id, user_id),
    CONSTRAINT ck_kb_member_role CHECK (role IN ('OWNER', 'EDITOR', 'VIEWER'))
);
CREATE INDEX idx_kb_member_user ON kb_member (tenant_id, user_id, kb_id);

CREATE TABLE metadata_schema (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT,
    name             VARCHAR(128) NOT NULL,
    schema_version   INTEGER      NOT NULL,
    schema_json      JSONB        NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at     TIMESTAMPTZ,
    CONSTRAINT uq_metadata_schema_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_metadata_schema_version UNIQUE (tenant_id, kb_id, name, schema_version),
    CONSTRAINT fk_metadata_schema_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT ck_metadata_schema_version CHECK (schema_version >= 1),
    CONSTRAINT ck_metadata_schema_json CHECK (jsonb_typeof(schema_json) = 'object'),
    CONSTRAINT ck_metadata_schema_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED'))
);

ALTER TABLE kb
    ADD CONSTRAINT fk_kb_metadata_schema
    FOREIGN KEY (tenant_id, metadata_schema_id)
    REFERENCES metadata_schema (tenant_id, id);

-- 3. Content source / sync / document --------------------------------

CREATE TABLE source_connection (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT        NOT NULL,
    name             VARCHAR(128)  NOT NULL,
    provider_key     VARCHAR(128)  NOT NULL,
    secret_ref       VARCHAR(512),
    config           JSONB         NOT NULL DEFAULT '{}'::jsonb,
    sync_mode        VARCHAR(16)   NOT NULL DEFAULT 'MANUAL',
    status           VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    cursor_value     TEXT,
    last_success_at  TIMESTAMPTZ,
    last_error_code  VARCHAR(64),
    last_error_at    TIMESTAMPTZ,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    row_version      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_source_connection_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_source_connection_name UNIQUE (tenant_id, kb_id, name),
    CONSTRAINT fk_source_connection_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT ck_source_connection_config CHECK (jsonb_typeof(config) = 'object'),
    CONSTRAINT ck_source_connection_mode CHECK (sync_mode IN ('MANUAL', 'SCHEDULED', 'WEBHOOK')),
    CONSTRAINT ck_source_connection_status CHECK (status IN ('ACTIVE', 'PAUSED', 'ERROR', 'REVOKED'))
);
CREATE INDEX idx_source_connection_status ON source_connection (tenant_id, status, last_success_at);

CREATE TABLE sync_job (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    connection_id    BIGINT       NOT NULL,
    job_type         VARCHAR(16)  NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'QUEUED',
    idempotency_key  VARCHAR(128) NOT NULL,
    cursor_before    TEXT,
    cursor_after     TEXT,
    discovered_count INTEGER      NOT NULL DEFAULT 0,
    created_count    INTEGER      NOT NULL DEFAULT 0,
    updated_count    INTEGER      NOT NULL DEFAULT 0,
    deleted_count    INTEGER      NOT NULL DEFAULT 0,
    failed_count     INTEGER      NOT NULL DEFAULT 0,
    error_code       VARCHAR(64),
    error_detail     JSONB,
    queued_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    started_at       TIMESTAMPTZ,
    finished_at      TIMESTAMPTZ,
    CONSTRAINT uq_sync_job_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_sync_job_idempotency UNIQUE (tenant_id, connection_id, idempotency_key),
    CONSTRAINT fk_sync_job_connection
        FOREIGN KEY (tenant_id, connection_id)
        REFERENCES source_connection (tenant_id, id),
    CONSTRAINT ck_sync_job_type CHECK (job_type IN ('FULL', 'INCREMENTAL', 'WEBHOOK', 'RECONCILE')),
    CONSTRAINT ck_sync_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'PARTIAL', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_sync_job_counts CHECK (
        discovered_count >= 0 AND created_count >= 0 AND updated_count >= 0
        AND deleted_count >= 0 AND failed_count >= 0
    ),
    CONSTRAINT ck_sync_job_error_json CHECK (error_detail IS NULL OR jsonb_typeof(error_detail) = 'object')
);
CREATE INDEX idx_sync_job_queue ON sync_job (tenant_id, status, queued_at);

CREATE TABLE source_object (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT        NOT NULL REFERENCES sys_tenant(id),
    connection_id      BIGINT        NOT NULL,
    external_id        VARCHAR(1024) NOT NULL,
    source_uri         VARCHAR(2048),
    source_version     VARCHAR(512),
    source_etag        VARCHAR(512),
    content_sha256     CHAR(64),
    source_acl         JSONB         NOT NULL DEFAULT '{}'::jsonb,
    document_id        BIGINT,
    last_sync_job_id   BIGINT,
    tombstoned         BOOLEAN       NOT NULL DEFAULT FALSE,
    source_updated_at  TIMESTAMPTZ,
    last_seen_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    row_version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_source_object_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_source_object_external UNIQUE (tenant_id, connection_id, external_id),
    CONSTRAINT fk_source_object_connection
        FOREIGN KEY (tenant_id, connection_id)
        REFERENCES source_connection (tenant_id, id),
    CONSTRAINT fk_source_object_sync_job
        FOREIGN KEY (tenant_id, last_sync_job_id)
        REFERENCES sync_job (tenant_id, id),
    CONSTRAINT ck_source_object_sha CHECK (content_sha256 IS NULL OR content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_source_object_acl CHECK (jsonb_typeof(source_acl) = 'object')
);
CREATE INDEX idx_source_object_document ON source_object (tenant_id, document_id);
CREATE INDEX idx_source_object_tombstone ON source_object (tenant_id, connection_id, tombstoned, last_seen_at);

CREATE TABLE document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES sys_tenant(id),
    kb_id               BIGINT        NOT NULL,
    title               VARCHAR(512)  NOT NULL,
    file_name           VARCHAR(512),
    file_ext            VARCHAR(32),
    mime_type           VARCHAR(256),
    source_type         VARCHAR(64)   NOT NULL DEFAULT 'UPLOAD',
    source_uri          VARCHAR(2048),
    owner_user_id       BIGINT,
    lifecycle_status    VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    review_status       VARCHAR(24)   NOT NULL DEFAULT 'DRAFT',
    authority_status    VARCHAR(24)   NOT NULL DEFAULT 'DRAFT',
    sensitivity         VARCHAR(24)   NOT NULL DEFAULT 'INTERNAL',
    data_region         VARCHAR(64),
    current_version_id  BIGINT,
    valid_from          TIMESTAMPTZ,
    valid_until         TIMESTAMPTZ,
    review_due_at       TIMESTAMPTZ,
    is_disabled         BOOLEAN       NOT NULL DEFAULT FALSE,
    policy_version      BIGINT        NOT NULL DEFAULT 1,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    row_version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_document_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_document_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT fk_document_owner
        FOREIGN KEY (tenant_id, owner_user_id)
        REFERENCES tenant_member (tenant_id, user_id),
    CONSTRAINT ck_document_lifecycle CHECK (lifecycle_status IN ('ACTIVE', 'ARCHIVED', 'DELETING', 'DELETED')),
    CONSTRAINT ck_document_review CHECK (review_status IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'WITHDRAWN')),
    CONSTRAINT ck_document_authority CHECK (authority_status IN ('DRAFT', 'AUTHORITATIVE', 'SUPERSEDED')),
    CONSTRAINT ck_document_sensitivity CHECK (sensitivity IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    CONSTRAINT ck_document_valid_range CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from),
    CONSTRAINT ck_document_policy_version CHECK (policy_version >= 1),
    CONSTRAINT ck_document_deleted_at CHECK (
        (lifecycle_status IN ('DELETING', 'DELETED') AND deleted_at IS NOT NULL)
        OR (lifecycle_status NOT IN ('DELETING', 'DELETED') AND deleted_at IS NULL)
    )
);
CREATE INDEX idx_document_retrievable
    ON document (tenant_id, kb_id, lifecycle_status, review_status, is_disabled, updated_at DESC);
CREATE INDEX idx_document_review_due
    ON document (tenant_id, review_due_at) WHERE review_due_at IS NOT NULL;

CREATE TABLE document_version (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT        NOT NULL REFERENCES sys_tenant(id),
    document_id        BIGINT        NOT NULL,
    version_no         INTEGER       NOT NULL,
    object_key         VARCHAR(1024) NOT NULL,
    content_sha256     CHAR(64)      NOT NULL,
    source_version     VARCHAR(512),
    file_size          BIGINT        NOT NULL,
    mime_type          VARCHAR(256)  NOT NULL,
    language           VARCHAR(32),
    ingest_status      VARCHAR(24)   NOT NULL DEFAULT 'QUARANTINED',
    safety_status      VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    safety_report      JSONB,
    parser_profile     VARCHAR(128),
    parser_revision    VARCHAR(128),
    chunk_count        INTEGER       NOT NULL DEFAULT 0,
    error_code         VARCHAR(64),
    error_detail       JSONB,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    ready_at           TIMESTAMPTZ,
    CONSTRAINT uq_document_version_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_document_version_document_id UNIQUE (tenant_id, document_id, id),
    CONSTRAINT uq_document_version_no UNIQUE (tenant_id, document_id, version_no),
    CONSTRAINT uq_document_version_object UNIQUE (tenant_id, object_key),
    CONSTRAINT fk_document_version_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id),
    CONSTRAINT ck_document_version_no CHECK (version_no >= 1),
    CONSTRAINT ck_document_version_size CHECK (file_size >= 0),
    CONSTRAINT ck_document_version_chunk_count CHECK (chunk_count >= 0),
    CONSTRAINT ck_document_version_sha CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_document_version_ingest CHECK (
        ingest_status IN ('QUARANTINED', 'SCANNING', 'PARSING', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'READY', 'FAILED', 'BLOCKED')
    ),
    CONSTRAINT ck_document_version_safety CHECK (safety_status IN ('PENDING', 'PASSED', 'BLOCKED', 'FAILED')),
    CONSTRAINT ck_document_version_safety_json CHECK (safety_report IS NULL OR jsonb_typeof(safety_report) = 'object'),
    CONSTRAINT ck_document_version_error_json CHECK (error_detail IS NULL OR jsonb_typeof(error_detail) = 'object')
);
CREATE INDEX idx_document_version_status ON document_version (tenant_id, ingest_status, created_at);

ALTER TABLE document
    ADD CONSTRAINT fk_document_current_version
    FOREIGN KEY (tenant_id, id, current_version_id)
    REFERENCES document_version (tenant_id, document_id, id);

ALTER TABLE source_object
    ADD CONSTRAINT fk_source_object_document
    FOREIGN KEY (tenant_id, document_id)
    REFERENCES document (tenant_id, id);

CREATE TABLE parse_task (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    document_id      BIGINT       NOT NULL,
    version_id       BIGINT       NOT NULL,
    task_type        VARCHAR(24)  NOT NULL DEFAULT 'INGEST',
    stage            VARCHAR(24)  NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'QUEUED',
    idempotency_key  VARCHAR(128) NOT NULL,
    attempt_count    INTEGER      NOT NULL DEFAULT 0,
    max_attempts     INTEGER      NOT NULL DEFAULT 3,
    progress_percent INTEGER      NOT NULL DEFAULT 0,
    worker_id        VARCHAR(128),
    lease_until      TIMESTAMPTZ,
    error_code       VARCHAR(64),
    error_detail     JSONB,
    queued_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    started_at       TIMESTAMPTZ,
    finished_at      TIMESTAMPTZ,
    CONSTRAINT uq_parse_task_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_parse_task_idempotency UNIQUE (tenant_id, task_type, idempotency_key),
    CONSTRAINT fk_parse_task_version
        FOREIGN KEY (tenant_id, document_id, version_id)
        REFERENCES document_version (tenant_id, document_id, id),
    CONSTRAINT ck_parse_task_type CHECK (task_type IN ('INGEST', 'REPARSE', 'REINDEX', 'DELETE')),
    CONSTRAINT ck_parse_task_stage CHECK (stage IN ('SAFETY', 'PARSING', 'OCR', 'CHUNKING', 'EMBEDDING', 'INDEXING', 'CLEANUP')),
    CONSTRAINT ck_parse_task_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_parse_task_attempts CHECK (attempt_count >= 0 AND max_attempts BETWEEN 1 AND 20),
    CONSTRAINT ck_parse_task_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_parse_task_error_json CHECK (error_detail IS NULL OR jsonb_typeof(error_detail) = 'object')
);
CREATE INDEX idx_parse_task_queue ON parse_task (tenant_id, status, queued_at);
CREATE INDEX idx_parse_task_lease ON parse_task (status, lease_until) WHERE status = 'RUNNING';

CREATE TABLE document_metadata (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    document_id      BIGINT      NOT NULL,
    schema_id        BIGINT      NOT NULL,
    schema_version   INTEGER     NOT NULL,
    values_json      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    validation_state VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    validated_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_document_metadata_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_document_metadata_schema
        FOREIGN KEY (tenant_id, schema_id)
        REFERENCES metadata_schema (tenant_id, id),
    CONSTRAINT uq_document_metadata UNIQUE (tenant_id, document_id),
    CONSTRAINT ck_document_metadata_version CHECK (schema_version >= 1),
    CONSTRAINT ck_document_metadata_values CHECK (jsonb_typeof(values_json) = 'object'),
    CONSTRAINT ck_document_metadata_state CHECK (validation_state IN ('PENDING', 'VALID', 'INVALID'))
);

CREATE TABLE document_acl (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    document_id      BIGINT       NOT NULL,
    principal_type   VARCHAR(24)  NOT NULL,
    principal_key    VARCHAR(256) NOT NULL,
    permission       VARCHAR(32)  NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_document_acl_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_document_acl UNIQUE (tenant_id, document_id, principal_type, principal_key, permission),
    CONSTRAINT ck_document_acl_principal CHECK (principal_type IN ('USER', 'ORG', 'TENANT_ROLE', 'KB_ROLE')),
    CONSTRAINT ck_document_acl_permission CHECK (permission IN ('VIEW_EXCERPT', 'VIEW_CONTENT', 'DOWNLOAD_ORIGINAL')),
    CONSTRAINT ck_document_acl_principal_key CHECK (btrim(principal_key) <> '')
);
CREATE INDEX idx_document_acl_principal
    ON document_acl (tenant_id, principal_type, principal_key, document_id);

CREATE TABLE document_review (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    document_id      BIGINT      NOT NULL,
    version_id       BIGINT      NOT NULL,
    action           VARCHAR(16) NOT NULL,
    actor_user_id    BIGINT,
    comment          VARCHAR(2048),
    policy_version   BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_review_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_document_review_version
        FOREIGN KEY (tenant_id, document_id, version_id)
        REFERENCES document_version (tenant_id, document_id, id),
    CONSTRAINT fk_document_review_actor
        FOREIGN KEY (tenant_id, actor_user_id)
        REFERENCES tenant_member (tenant_id, user_id),
    CONSTRAINT ck_document_review_action CHECK (action IN ('SUBMIT', 'APPROVE', 'REJECT', 'WITHDRAW')),
    CONSTRAINT ck_document_review_policy CHECK (policy_version >= 1)
);
CREATE INDEX idx_document_review_history ON document_review (tenant_id, document_id, created_at DESC);

CREATE TABLE legal_hold (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL REFERENCES sys_tenant(id),
    name             VARCHAR(128)  NOT NULL,
    reason           VARCHAR(2048) NOT NULL,
    status           VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    created_by       BIGINT,
    released_by      BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    released_at      TIMESTAMPTZ,
    CONSTRAINT uq_legal_hold_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_legal_hold_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_legal_hold_status CHECK (status IN ('ACTIVE', 'RELEASED')),
    CONSTRAINT ck_legal_hold_release CHECK (
        (status = 'ACTIVE' AND released_at IS NULL)
        OR (status = 'RELEASED' AND released_at IS NOT NULL)
    )
);

CREATE TABLE legal_hold_document (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    legal_hold_id    BIGINT      NOT NULL,
    document_id      BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_legal_hold_document_hold
        FOREIGN KEY (tenant_id, legal_hold_id)
        REFERENCES legal_hold (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_legal_hold_document_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id),
    CONSTRAINT uq_legal_hold_document UNIQUE (tenant_id, legal_hold_id, document_id)
);

-- 4. Chunk / index / policy ------------------------------------------

CREATE TABLE chunk_meta (
    chunk_id             CHAR(64)      PRIMARY KEY,
    tenant_id            BIGINT        NOT NULL REFERENCES sys_tenant(id),
    kb_id                BIGINT        NOT NULL,
    document_id          BIGINT        NOT NULL,
    version_id           BIGINT        NOT NULL,
    index_profile_id     BIGINT        NOT NULL,
    ordinal              INTEGER       NOT NULL,
    block_type           VARCHAR(24)   NOT NULL,
    page_no              INTEGER,
    section_path         JSONB         NOT NULL DEFAULT '[]'::jsonb,
    location_json        JSONB         NOT NULL DEFAULT '{}'::jsonb,
    chunk_text           TEXT          NOT NULL,
    text_sha256          CHAR(64)      NOT NULL,
    token_count          INTEGER       NOT NULL,
    source_updated_at    TIMESTAMPTZ,
    policy_version       BIGINT        NOT NULL,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_chunk_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT fk_chunk_version
        FOREIGN KEY (tenant_id, document_id, version_id)
        REFERENCES document_version (tenant_id, document_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_index_profile
        FOREIGN KEY (tenant_id, index_profile_id)
        REFERENCES index_profile (tenant_id, id),
    CONSTRAINT uq_chunk_ordinal UNIQUE (tenant_id, version_id, index_profile_id, ordinal),
    CONSTRAINT ck_chunk_id CHECK (chunk_id ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_chunk_text_sha CHECK (text_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_chunk_ordinal CHECK (ordinal >= 0),
    CONSTRAINT ck_chunk_token_count CHECK (token_count > 0),
    CONSTRAINT ck_chunk_page CHECK (page_no IS NULL OR page_no >= 1),
    CONSTRAINT ck_chunk_section_json CHECK (jsonb_typeof(section_path) = 'array'),
    CONSTRAINT ck_chunk_location_json CHECK (jsonb_typeof(location_json) = 'object'),
    CONSTRAINT ck_chunk_policy_version CHECK (policy_version >= 1)
);
CREATE INDEX idx_chunk_document ON chunk_meta (tenant_id, document_id, version_id, ordinal);
CREATE INDEX idx_chunk_kb_profile ON chunk_meta (tenant_id, kb_id, index_profile_id);

CREATE TABLE index_build (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT        NOT NULL,
    index_profile_id BIGINT        NOT NULL,
    build_no         INTEGER       NOT NULL,
    physical_name    VARCHAR(256)  NOT NULL,
    read_alias       VARCHAR(256)  NOT NULL,
    status           VARCHAR(16)   NOT NULL DEFAULT 'QUEUED',
    idempotency_key  VARCHAR(128)  NOT NULL,
    document_count   BIGINT        NOT NULL DEFAULT 0,
    chunk_count      BIGINT        NOT NULL DEFAULT 0,
    failed_count     BIGINT        NOT NULL DEFAULT 0,
    quality_report   JSONB,
    error_code       VARCHAR(64),
    error_detail     JSONB,
    queued_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    started_at       TIMESTAMPTZ,
    finished_at      TIMESTAMPTZ,
    published_at     TIMESTAMPTZ,
    retired_at       TIMESTAMPTZ,
    CONSTRAINT uq_index_build_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_index_build_no UNIQUE (tenant_id, kb_id, index_profile_id, build_no),
    CONSTRAINT uq_index_build_name UNIQUE (physical_name),
    CONSTRAINT uq_index_build_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT fk_index_build_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT fk_index_build_profile
        FOREIGN KEY (tenant_id, index_profile_id)
        REFERENCES index_profile (tenant_id, id),
    CONSTRAINT ck_index_build_no CHECK (build_no >= 1),
    CONSTRAINT ck_index_build_status CHECK (status IN ('QUEUED', 'BUILDING', 'VALIDATING', 'READY', 'PUBLISHED', 'FAILED', 'RETIRED')),
    CONSTRAINT ck_index_build_counts CHECK (document_count >= 0 AND chunk_count >= 0 AND failed_count >= 0),
    CONSTRAINT ck_index_build_quality_json CHECK (quality_report IS NULL OR jsonb_typeof(quality_report) = 'object'),
    CONSTRAINT ck_index_build_error_json CHECK (error_detail IS NULL OR jsonb_typeof(error_detail) = 'object')
);
CREATE INDEX idx_index_build_status ON index_build (tenant_id, kb_id, status, queued_at);

ALTER TABLE kb
    ADD CONSTRAINT fk_kb_active_index_build
    FOREIGN KEY (tenant_id, active_index_build_id)
    REFERENCES index_build (tenant_id, id);

CREATE TABLE policy_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    snapshot_key     VARCHAR(64)  NOT NULL,
    subject_type     VARCHAR(16)  NOT NULL,
    subject_key      VARCHAR(256) NOT NULL,
    permission       VARCHAR(32)  NOT NULL,
    kb_ids           JSONB        NOT NULL,
    policy_version   BIGINT       NOT NULL,
    allowed_count    INTEGER      NOT NULL,
    allowed_checksum CHAR(64)     NOT NULL,
    cache_ref        VARCHAR(512) NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    expires_at       TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    invalidated_at   TIMESTAMPTZ,
    CONSTRAINT uq_policy_snapshot_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_policy_snapshot_key UNIQUE (snapshot_key),
    CONSTRAINT ck_policy_snapshot_subject CHECK (subject_type IN ('USER', 'API_KEY', 'SERVICE')),
    CONSTRAINT ck_policy_snapshot_permission CHECK (permission IN ('VIEW_EXCERPT', 'VIEW_CONTENT')),
    CONSTRAINT ck_policy_snapshot_kb_ids CHECK (jsonb_typeof(kb_ids) = 'array'),
    CONSTRAINT ck_policy_snapshot_version CHECK (policy_version >= 1),
    CONSTRAINT ck_policy_snapshot_count CHECK (allowed_count >= 0),
    CONSTRAINT ck_policy_snapshot_checksum CHECK (allowed_checksum ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_policy_snapshot_status CHECK (status IN ('ACTIVE', 'INVALIDATED', 'EXPIRED')),
    CONSTRAINT ck_policy_snapshot_expiry CHECK (expires_at > created_at)
);
CREATE INDEX idx_policy_snapshot_subject
    ON policy_snapshot (tenant_id, subject_type, subject_key, status, expires_at);

-- 5. Conversation / analytics ----------------------------------------

CREATE TABLE chat_session (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    user_id          BIGINT       NOT NULL,
    title            VARCHAR(256),
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    row_version      BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_chat_session_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_chat_session_user
        FOREIGN KEY (tenant_id, user_id)
        REFERENCES tenant_member (tenant_id, user_id),
    CONSTRAINT ck_chat_session_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED')),
    CONSTRAINT ck_chat_session_deleted_at CHECK (
        (status = 'DELETED' AND deleted_at IS NOT NULL)
        OR (status <> 'DELETED' AND deleted_at IS NULL)
    )
);
CREATE INDEX idx_chat_session_user ON chat_session (tenant_id, user_id, updated_at DESC);

CREATE TABLE chat_session_kb (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    session_id       BIGINT      NOT NULL,
    kb_id            BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_session_kb_session
        FOREIGN KEY (tenant_id, session_id)
        REFERENCES chat_session (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_session_kb_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT uq_chat_session_kb UNIQUE (tenant_id, session_id, kb_id)
);

CREATE TABLE chat_message (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT         NOT NULL REFERENCES sys_tenant(id),
    session_id            BIGINT         NOT NULL,
    seq                   INTEGER        NOT NULL,
    role                  VARCHAR(16)    NOT NULL,
    content               TEXT           NOT NULL,
    answer_status         VARCHAR(24),
    confidence            NUMERIC(7,6),
    feedback              SMALLINT       NOT NULL DEFAULT 0,
    feedback_reason       VARCHAR(1024),
    token_in              BIGINT         NOT NULL DEFAULT 0,
    token_out             BIGINT         NOT NULL DEFAULT 0,
    model_provider        VARCHAR(128),
    model_name            VARCHAR(256),
    model_revision        VARCHAR(256),
    prompt_version        VARCHAR(64),
    index_profile_version INTEGER,
    policy_version        BIGINT,
    trace_id              VARCHAR(64),
    created_at            TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_chat_message_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_chat_message_seq UNIQUE (tenant_id, session_id, seq),
    CONSTRAINT fk_chat_message_session
        FOREIGN KEY (tenant_id, session_id)
        REFERENCES chat_session (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_chat_message_seq CHECK (seq >= 1),
    CONSTRAINT ck_chat_message_role CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_chat_message_answer CHECK (answer_status IS NULL OR answer_status IN ('ANSWERED', 'NO_ANSWER', 'LOW_CONFIDENCE', 'CANCELLED', 'BLOCKED')),
    CONSTRAINT ck_chat_message_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_chat_message_feedback CHECK (feedback IN (-1, 0, 1)),
    CONSTRAINT ck_chat_message_tokens CHECK (token_in >= 0 AND token_out >= 0),
    CONSTRAINT ck_chat_message_policy CHECK (policy_version IS NULL OR policy_version >= 1)
);
CREATE INDEX idx_chat_message_session ON chat_message (tenant_id, session_id, seq);

CREATE TABLE chat_message_source (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT         NOT NULL REFERENCES sys_tenant(id),
    message_id       BIGINT         NOT NULL,
    document_id      BIGINT         NOT NULL,
    version_id       BIGINT         NOT NULL,
    chunk_id         CHAR(64)       NOT NULL,
    source_rank      INTEGER        NOT NULL,
    score            NUMERIC(12,8),
    location_json    JSONB          NOT NULL DEFAULT '{}'::jsonb,
    cited_text_sha256 CHAR(64)      NOT NULL,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_chat_source_message
        FOREIGN KEY (tenant_id, message_id)
        REFERENCES chat_message (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_source_version
        FOREIGN KEY (tenant_id, document_id, version_id)
        REFERENCES document_version (tenant_id, document_id, id),
    CONSTRAINT uq_chat_source_rank UNIQUE (tenant_id, message_id, source_rank),
    CONSTRAINT ck_chat_source_chunk CHECK (chunk_id ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_chat_source_rank CHECK (source_rank >= 1),
    CONSTRAINT ck_chat_source_score CHECK (score IS NULL OR score >= 0),
    CONSTRAINT ck_chat_source_location CHECK (jsonb_typeof(location_json) = 'object'),
    CONSTRAINT ck_chat_source_text_sha CHECK (cited_text_sha256 ~ '^[0-9a-f]{64}$')
);
CREATE INDEX idx_chat_source_document ON chat_message_source (tenant_id, document_id, version_id);

CREATE TABLE usage_daily (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT         NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT,
    stat_date        DATE           NOT NULL,
    search_count     BIGINT         NOT NULL DEFAULT 0,
    qa_count         BIGINT         NOT NULL DEFAULT 0,
    no_answer_count  BIGINT         NOT NULL DEFAULT 0,
    low_conf_count   BIGINT         NOT NULL DEFAULT 0,
    token_in         BIGINT         NOT NULL DEFAULT 0,
    token_out        BIGINT         NOT NULL DEFAULT 0,
    active_users     INTEGER        NOT NULL DEFAULT 0,
    cost             NUMERIC(18,6)  NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_usage_daily_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT uq_usage_daily UNIQUE NULLS NOT DISTINCT (tenant_id, kb_id, stat_date),
    CONSTRAINT ck_usage_daily_counts CHECK (
        search_count >= 0 AND qa_count >= 0 AND no_answer_count >= 0
        AND low_conf_count >= 0 AND token_in >= 0 AND token_out >= 0
        AND active_users >= 0 AND cost >= 0
    )
);

CREATE TABLE cost_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT         NOT NULL REFERENCES sys_tenant(id),
    kb_id            BIGINT,
    request_id       VARCHAR(64),
    scene            VARCHAR(32)    NOT NULL,
    provider_key     VARCHAR(128)   NOT NULL,
    model_name       VARCHAR(256)   NOT NULL,
    model_revision   VARCHAR(256),
    route_reason     VARCHAR(64),
    token_in         BIGINT         NOT NULL DEFAULT 0,
    token_out        BIGINT         NOT NULL DEFAULT 0,
    unit_price_in    NUMERIC(18,9)  NOT NULL DEFAULT 0,
    unit_price_out   NUMERIC(18,9)  NOT NULL DEFAULT 0,
    cost             NUMERIC(18,6)  NOT NULL DEFAULT 0,
    currency         CHAR(3)        NOT NULL DEFAULT 'CNY',
    latency_ms       INTEGER,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_cost_record_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id),
    CONSTRAINT ck_cost_scene CHECK (scene IN ('EMBEDDING', 'RERANK', 'LLM', 'OCR')),
    CONSTRAINT ck_cost_numbers CHECK (
        token_in >= 0 AND token_out >= 0 AND unit_price_in >= 0
        AND unit_price_out >= 0 AND cost >= 0 AND (latency_ms IS NULL OR latency_ms >= 0)
    ),
    CONSTRAINT ck_cost_currency CHECK (currency ~ '^[A-Z]{3}$')
);
CREATE INDEX idx_cost_record_time ON cost_record (tenant_id, created_at DESC);

CREATE TABLE model_route_config (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL REFERENCES sys_tenant(id),
    scene              VARCHAR(32)  NOT NULL,
    purpose            VARCHAR(64)  NOT NULL DEFAULT 'DEFAULT',
    rule_order         INTEGER      NOT NULL DEFAULT 100,
    condition_json     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    target_provider    VARCHAR(128) NOT NULL,
    target_model       VARCHAR(256) NOT NULL,
    fallback_provider  VARCHAR(128),
    fallback_model     VARCHAR(256),
    max_sensitivity    VARCHAR(24)  NOT NULL DEFAULT 'INTERNAL',
    data_region        VARCHAR(64)  NOT NULL DEFAULT 'default',
    timeout_ms         INTEGER      NOT NULL DEFAULT 10000,
    status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    row_version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_model_route_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_model_route_order UNIQUE (tenant_id, scene, purpose, rule_order),
    CONSTRAINT ck_model_route_scene CHECK (scene IN ('LLM', 'RERANK', 'OCR')),
    CONSTRAINT ck_model_route_condition CHECK (jsonb_typeof(condition_json) = 'object'),
    CONSTRAINT ck_model_route_sensitivity CHECK (max_sensitivity IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')),
    CONSTRAINT ck_model_route_timeout CHECK (timeout_ms BETWEEN 100 AND 300000),
    CONSTRAINT ck_model_route_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT ck_model_route_fallback_pair CHECK (
        (fallback_provider IS NULL AND fallback_model IS NULL)
        OR (fallback_provider IS NOT NULL AND fallback_model IS NOT NULL)
    )
);
CREATE INDEX idx_model_route_match ON model_route_config (tenant_id, scene, purpose, status, rule_order);

-- 6. Integration / audit / event -------------------------------------

CREATE TABLE api_key (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    name             VARCHAR(128) NOT NULL,
    key_digest       CHAR(64)     NOT NULL,
    key_prefix       VARCHAR(16)  NOT NULL,
    scopes           JSONB        NOT NULL,
    rate_limit_per_minute INTEGER  NOT NULL DEFAULT 60,
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    expires_at       TIMESTAMPTZ,
    last_used_at     TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_api_key_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_api_key_digest UNIQUE (key_digest),
    CONSTRAINT uq_api_key_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_api_key_digest CHECK (key_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_api_key_scopes CHECK (jsonb_typeof(scopes) = 'array'),
    CONSTRAINT ck_api_key_rate CHECK (rate_limit_per_minute BETWEEN 1 AND 100000),
    CONSTRAINT ck_api_key_status CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    CONSTRAINT ck_api_key_revoked_at CHECK (
        (status = 'REVOKED' AND revoked_at IS NOT NULL)
        OR status <> 'REVOKED'
    )
);
CREATE INDEX idx_api_key_lookup ON api_key (key_prefix, status);

CREATE TABLE api_key_kb (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    api_key_id       BIGINT      NOT NULL,
    kb_id            BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_api_key_kb_key
        FOREIGN KEY (tenant_id, api_key_id)
        REFERENCES api_key (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_api_key_kb_kb
        FOREIGN KEY (tenant_id, kb_id)
        REFERENCES kb (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_api_key_kb UNIQUE (tenant_id, api_key_id, kb_id)
);

CREATE TABLE idempotency_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    operation        VARCHAR(64)  NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_sha256   CHAR(64)     NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'PROCESSING',
    resource_type    VARCHAR(64),
    resource_id      VARCHAR(128),
    response_status  INTEGER,
    response_sha256  CHAR(64),
    expires_at       TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_idempotency_record UNIQUE (tenant_id, operation, idempotency_key),
    CONSTRAINT ck_idempotency_request_sha CHECK (request_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_response_sha CHECK (response_sha256 IS NULL OR response_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_status CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_idempotency_expiry CHECK (expires_at > created_at)
);
CREATE INDEX idx_idempotency_expiry ON idempotency_record (tenant_id, expires_at);

CREATE TABLE audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL REFERENCES sys_tenant(id),
    actor_type       VARCHAR(16)   NOT NULL,
    actor_id         VARCHAR(256),
    credential_id    VARCHAR(256),
    action           VARCHAR(128)  NOT NULL,
    resource_type    VARCHAR(64)   NOT NULL,
    resource_id      VARCHAR(256),
    result           VARCHAR(16)   NOT NULL,
    reason_code      VARCHAR(64),
    request_id       VARCHAR(64),
    trace_id         VARCHAR(64),
    source_ip        INET,
    policy_version   BIGINT,
    detail           JSONB         NOT NULL DEFAULT '{}'::jsonb,
    occurred_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_audit_log_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT ck_audit_actor CHECK (actor_type IN ('USER', 'API_KEY', 'SERVICE', 'SYSTEM')),
    CONSTRAINT ck_audit_result CHECK (result IN ('SUCCEEDED', 'DENIED', 'FAILED')),
    CONSTRAINT ck_audit_policy CHECK (policy_version IS NULL OR policy_version >= 1),
    CONSTRAINT ck_audit_detail CHECK (jsonb_typeof(detail) = 'object')
);
CREATE INDEX idx_audit_time ON audit_log (tenant_id, occurred_at DESC);
CREATE INDEX idx_audit_actor ON audit_log (tenant_id, actor_type, actor_id, occurred_at DESC);
CREATE INDEX idx_audit_resource ON audit_log (tenant_id, resource_type, resource_id, occurred_at DESC);

CREATE TABLE outbox_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL REFERENCES sys_tenant(id),
    event_id          UUID          NOT NULL DEFAULT gen_random_uuid(),
    aggregate_type    VARCHAR(64)   NOT NULL,
    aggregate_id      VARCHAR(128)  NOT NULL,
    aggregate_version BIGINT        NOT NULL,
    event_type        VARCHAR(128)  NOT NULL,
    topic             VARCHAR(32)   NOT NULL DEFAULT 'general',
    payload           JSONB         NOT NULL,
    status            VARCHAR(16)   NOT NULL DEFAULT 'NEW',
    attempt_count     INTEGER       NOT NULL DEFAULT 0,
    available_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    occurred_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    published_at      TIMESTAMPTZ,
    last_error_code   VARCHAR(64),
    dead_letter_at    TIMESTAMPTZ,
    CONSTRAINT uq_outbox_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_outbox_event_id UNIQUE (event_id),
    CONSTRAINT uq_outbox_aggregate_event UNIQUE (
        tenant_id, aggregate_type, aggregate_id, aggregate_version, event_type
    ),
    CONSTRAINT ck_outbox_version CHECK (aggregate_version >= 1),
    CONSTRAINT ck_outbox_payload CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_status CHECK (status IN ('NEW', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD')),
    CONSTRAINT ck_outbox_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_topic CHECK (topic IN (
        'sync', 'ingestion', 'index', 'webhook', 'governance', 'general'
    ))
);
CREATE INDEX idx_outbox_dispatch ON outbox_event (status, available_at, id)
    WHERE status IN ('NEW', 'FAILED');
CREATE INDEX idx_outbox_claim ON outbox_event (topic, status, available_at)
    WHERE status IN ('NEW', 'FAILED');

-- 7. Deletion evidence ------------------------------------------------

CREATE TABLE deletion_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES sys_tenant(id),
    resource_type       VARCHAR(24)   NOT NULL,
    resource_id         VARCHAR(256)  NOT NULL,
    reason              VARCHAR(2048) NOT NULL,
    requested_by        BIGINT,
    idempotency_key     VARCHAR(128)  NOT NULL,
    status              VARCHAR(16)   NOT NULL DEFAULT 'QUEUED',
    preview_json        JSONB         NOT NULL DEFAULT '{}'::jsonb,
    legal_hold_blocked  BOOLEAN       NOT NULL DEFAULT FALSE,
    blocked_reason_code VARCHAR(64),
    target_count        INTEGER       NOT NULL DEFAULT 0,
    completed_count     INTEGER       NOT NULL DEFAULT 0,
    failed_count        INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    CONSTRAINT uq_deletion_task_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_deletion_task_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_deletion_task_resource CHECK (resource_type IN ('TENANT', 'KB', 'DOCUMENT', 'VERSION')),
    CONSTRAINT ck_deletion_task_status CHECK (status IN ('QUEUED', 'RUNNING', 'BLOCKED', 'PARTIAL', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_deletion_task_preview CHECK (jsonb_typeof(preview_json) = 'object'),
    CONSTRAINT ck_deletion_task_counts CHECK (
        target_count >= 0 AND completed_count >= 0 AND failed_count >= 0
        AND completed_count + failed_count <= target_count
    ),
    CONSTRAINT ck_deletion_task_blocked CHECK (
        (status = 'BLOCKED' AND blocked_reason_code IS NOT NULL)
        OR status <> 'BLOCKED'
    )
);
CREATE INDEX idx_deletion_task_queue
    ON deletion_task (tenant_id, status, created_at)
    WHERE status IN ('QUEUED', 'RUNNING', 'PARTIAL', 'FAILED');

CREATE TABLE deletion_target (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT        NOT NULL REFERENCES sys_tenant(id),
    deletion_task_id   BIGINT        NOT NULL,
    target_type        VARCHAR(24)   NOT NULL,
    target_key         VARCHAR(1024) NOT NULL,
    status             VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    expected_count     BIGINT        NOT NULL DEFAULT 1,
    deleted_count      BIGINT        NOT NULL DEFAULT 0,
    result_sha256      CHAR(64),
    backup_expires_at  TIMESTAMPTZ,
    last_error_code    VARCHAR(64),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    completed_at       TIMESTAMPTZ,
    CONSTRAINT fk_deletion_target_task
        FOREIGN KEY (tenant_id, deletion_task_id)
        REFERENCES deletion_task (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_deletion_target UNIQUE (tenant_id, deletion_task_id, target_type, target_key),
    CONSTRAINT ck_deletion_target_type CHECK (
        target_type IN ('OBJECT', 'CHUNK_META', 'SEARCH_INDEX', 'CACHE', 'PREVIEW', 'SOURCE_LINK', 'BACKUP_EXCEPTION')
    ),
    CONSTRAINT ck_deletion_target_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'RETAINED')),
    CONSTRAINT ck_deletion_target_counts CHECK (expected_count >= 0 AND deleted_count >= 0 AND deleted_count <= expected_count),
    CONSTRAINT ck_deletion_target_sha CHECK (result_sha256 IS NULL OR result_sha256 ~ '^[0-9a-f]{64}$')
);
CREATE INDEX idx_deletion_target_queue
    ON deletion_target (tenant_id, status, updated_at)
    WHERE status IN ('PENDING', 'RUNNING', 'FAILED');

CREATE TABLE deletion_receipt (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL REFERENCES sys_tenant(id),
    deletion_task_id   BIGINT       NOT NULL,
    result             VARCHAR(16)  NOT NULL,
    summary_json       JSONB        NOT NULL,
    receipt_sha256     CHAR(64)     NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_deletion_receipt_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_deletion_receipt_task UNIQUE (tenant_id, deletion_task_id),
    CONSTRAINT fk_deletion_receipt_task
        FOREIGN KEY (tenant_id, deletion_task_id)
        REFERENCES deletion_task (tenant_id, id),
    CONSTRAINT ck_deletion_receipt_result CHECK (result IN ('SUCCEEDED', 'PARTIAL', 'BLOCKED')),
    CONSTRAINT ck_deletion_receipt_summary CHECK (jsonb_typeof(summary_json) = 'object'),
    CONSTRAINT ck_deletion_receipt_sha CHECK (receipt_sha256 ~ '^[0-9a-f]{64}$')
);

-- 8. Auxiliary knowledge / webhook -----------------------------------

CREATE TABLE tag (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    name             VARCHAR(128) NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tag_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_tag_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_tag_name CHECK (btrim(name) <> '')
);

CREATE TABLE document_tag (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    document_id      BIGINT      NOT NULL,
    tag_id           BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_document_tag_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_document_tag_tag
        FOREIGN KEY (tenant_id, tag_id)
        REFERENCES tag (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_document_tag UNIQUE (tenant_id, document_id, tag_id)
);
CREATE INDEX idx_document_tag_tag ON document_tag (tenant_id, tag_id, document_id);

CREATE TABLE user_favorite (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL REFERENCES sys_tenant(id),
    user_id          BIGINT      NOT NULL,
    document_id      BIGINT      NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_favorite_user
        FOREIGN KEY (tenant_id, user_id)
        REFERENCES tenant_member (tenant_id, user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_favorite_document
        FOREIGN KEY (tenant_id, document_id)
        REFERENCES document (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_user_favorite UNIQUE (tenant_id, user_id, document_id)
);
CREATE INDEX idx_user_favorite_user ON user_favorite (tenant_id, user_id, created_at DESC);

CREATE TABLE webhook_subscription (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL REFERENCES sys_tenant(id),
    name             VARCHAR(128)  NOT NULL,
    target_url       VARCHAR(2048) NOT NULL,
    event_types      JSONB         NOT NULL,
    secret_ref       VARCHAR(512)  NOT NULL,
    status           VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    created_by       BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    row_version      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uq_webhook_subscription_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_webhook_subscription_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_webhook_target_https CHECK (target_url ~ '^https://'),
    CONSTRAINT ck_webhook_event_types CHECK (jsonb_typeof(event_types) = 'array'),
    CONSTRAINT ck_webhook_subscription_status CHECK (status IN ('ACTIVE', 'PAUSED', 'REVOKED'))
);

CREATE TABLE webhook_delivery (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    subscription_id  BIGINT       NOT NULL,
    event_id         BIGINT       NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempt_count    INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    http_status      INTEGER,
    response_sha256  CHAR(64),
    last_error_code  VARCHAR(64),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    delivered_at     TIMESTAMPTZ,
    CONSTRAINT uq_webhook_delivery_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_webhook_delivery_event UNIQUE (tenant_id, subscription_id, event_id),
    CONSTRAINT fk_webhook_delivery_subscription
        FOREIGN KEY (tenant_id, subscription_id)
        REFERENCES webhook_subscription (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_webhook_delivery_event
        FOREIGN KEY (tenant_id, event_id)
        REFERENCES outbox_event (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_webhook_delivery_status CHECK (status IN ('PENDING', 'SENDING', 'SUCCEEDED', 'RETRY', 'DEAD')),
    CONSTRAINT ck_webhook_delivery_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_webhook_delivery_http CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
    CONSTRAINT ck_webhook_delivery_sha CHECK (response_sha256 IS NULL OR response_sha256 ~ '^[0-9a-f]{64}$')
);
CREATE INDEX idx_webhook_delivery_queue
    ON webhook_delivery (status, next_attempt_at, id) WHERE status IN ('PENDING', 'RETRY');

-- 9. Comments ---------------------------------------------------------

COMMENT ON TABLE sys_user IS '全局身份；租户关系由 tenant_member 表达，不保存企业密码';
COMMENT ON TABLE tenant_member IS '用户加入租户的生命周期关系';
COMMENT ON TABLE document IS '文档业务身份、治理状态与当前不可变版本指针';
COMMENT ON TABLE document_version IS '不可变原始内容版本及安全/摄取状态';
COMMENT ON TABLE source_object IS '外部内容对象、版本/ETag、源 ACL 和删除墓碑';
COMMENT ON TABLE index_profile IS '不可变 embedding/chunker/search 配置版本';
COMMENT ON TABLE policy_snapshot IS '短期检索授权快照元数据；允许文档集合保存在 cache_ref';
COMMENT ON TABLE outbox_event IS '与领域变更同事务提交的可靠事件发件箱';
COMMENT ON TABLE audit_log IS '追加写安全/业务审计；detail 禁止存原文和秘密';
COMMENT ON TABLE deletion_receipt IS '删除目标处置结果的追加写摘要与校验和；备份例外须显式记录';

-- 10. updated_at triggers --------------------------------------------

DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'sys_tenant', 'sys_user', 'identity_account', 'identity_provider',
        'tenant_member', 'sys_org', 'retention_policy', 'kb', 'kb_member',
        'source_connection', 'source_object', 'document', 'document_metadata',
        'chat_session', 'usage_daily', 'model_route_config', 'idempotency_record',
        'deletion_target', 'webhook_subscription', 'webhook_delivery'
    ]
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            table_name, table_name
        );
    END LOOP;
END;
$$;

-- 11. Runtime privileges ---------------------------------------------

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ragkb_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ragkb_app;
GRANT EXECUTE ON FUNCTION set_updated_at() TO ragkb_app;

-- 追加写记录不允许 runtime role 修改/删除；清理由受审计 maintenance role 执行。
REVOKE UPDATE, DELETE ON audit_log FROM ragkb_app;
REVOKE UPDATE, DELETE ON document_review FROM ragkb_app;
REVOKE UPDATE, DELETE ON chat_message_source FROM ragkb_app;
REVOKE UPDATE, DELETE ON deletion_receipt FROM ragkb_app;

COMMIT;
RESET ROLE;

-- 静态校验建议：
--   SELECT count(*) FROM information_schema.tables
--   WHERE table_schema='public' AND table_type='BASE TABLE';
--   SELECT conrelid::regclass, conname FROM pg_constraint
--   WHERE contype IN ('f','c') ORDER BY conrelid::regclass::text, conname;
--
-- 启用 RLS 前必须验证应用为每个事务设置 app.tenant_id，见 04-enable-tenant-rls.sql。
