-- =====================================================================
-- v0.1 -> v0.2 企业通用化迁移：Phase A / Expand（仅加法）
--
-- 适用范围：旧 v0.1 DDL，特征为 sys_user.tenant_id 存在且 tenant_member 不存在。
-- 不适用于新装 v0.2；新装请执行 00、01、02。
--
-- 重要：
--   1. 本脚本不删除、重命名或改写旧业务列，不会自动完成应用切流。
--   2. 新旧身份模型并存期间，应用必须双写并核对；切流/收缩另行评审。
--   3. embedding_dimension 与 model_revision 无法从 v0.1 可靠推断，迁移档案保持 DRAFT，
--      必须完成重建与质量门禁后才能激活。
--   4. 执行前必须备份、演练、统计行数并取得变更窗口批准。
-- =====================================================================

\set ON_ERROR_STOP on

SELECT (
    EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'sys_user' AND column_name = 'tenant_id'
    )
    AND NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'tenant_member'
    )
) AS legacy_v01 \gset

\if :legacy_v01

BEGIN;
SELECT pg_advisory_xact_lock(hashtext('ragkb:v0.2:expand'));

CREATE TABLE IF NOT EXISTS schema_migration (
    version         VARCHAR(64) PRIMARY KEY,
    phase           VARCHAR(16) NOT NULL,
    checksum        VARCHAR(128),
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_by      TEXT        NOT NULL DEFAULT current_user,
    notes           TEXT
);

-- Tenant control-plane attributes. Legacy numeric status remains untouched.
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS code VARCHAR(64);
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS deployment_mode VARCHAR(16);
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS data_region VARCHAR(64);
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS lifecycle_status_v2 VARCHAR(16);
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS policy_version BIGINT;
ALTER TABLE sys_tenant ADD COLUMN IF NOT EXISTS row_version BIGINT;

UPDATE sys_tenant
SET code = COALESCE(code, 'tenant-' || id::text),
    deployment_mode = COALESCE(deployment_mode, 'PRIVATE'),
    data_region = COALESCE(data_region, 'default'),
    lifecycle_status_v2 = COALESCE(lifecycle_status_v2, 'ACTIVE'),
    policy_version = COALESCE(policy_version, 1),
    row_version = COALESCE(row_version, 0)
WHERE code IS NULL
   OR deployment_mode IS NULL
   OR data_region IS NULL
   OR lifecycle_status_v2 IS NULL
   OR policy_version IS NULL
   OR row_version IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_sys_tenant_code_v2 ON sys_tenant (code);

-- Parallel identity model. legacy_user_id supplies an auditable back-reference.
CREATE TABLE IF NOT EXISTS identity_user_v2 (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_user_id   BIGINT NOT NULL UNIQUE REFERENCES sys_user(id),
    primary_email    VARCHAR(254),
    display_name     VARCHAR(128),
    status           VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_identity_user_v2_status CHECK (status IN ('ACTIVE', 'DISABLED', 'DELETED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_user_v2_email
    ON identity_user_v2 (lower(primary_email)) WHERE primary_email IS NOT NULL;

INSERT INTO identity_user_v2 (legacy_user_id, primary_email, display_name, status)
SELECT id,
       NULLIF(email, ''),
       COALESCE(NULLIF(nickname, ''), NULLIF(email, ''), 'user-' || id::text),
       CASE WHEN status = 1 THEN 'ACTIVE' ELSE 'DISABLED' END
FROM sys_user
ON CONFLICT (legacy_user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS tenant_member_v2 (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL REFERENCES sys_tenant(id),
    identity_user_id BIGINT NOT NULL REFERENCES identity_user_v2(id),
    legacy_user_id   BIGINT NOT NULL REFERENCES sys_user(id),
    status           VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    joined_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_member_v2_user UNIQUE (tenant_id, identity_user_id),
    CONSTRAINT uq_tenant_member_v2_legacy UNIQUE (tenant_id, legacy_user_id),
    CONSTRAINT ck_tenant_member_v2_status CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED'))
);

INSERT INTO tenant_member_v2 (tenant_id, identity_user_id, legacy_user_id, status)
SELECT u.tenant_id, iu.id, u.id,
       CASE WHEN u.status = 1 THEN 'ACTIVE' ELSE 'SUSPENDED' END
FROM sys_user u
JOIN identity_user_v2 iu ON iu.legacy_user_id = u.id
ON CONFLICT (tenant_id, legacy_user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS tenant_member_role_v2 (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL REFERENCES sys_tenant(id),
    identity_user_id BIGINT NOT NULL REFERENCES identity_user_v2(id),
    role             VARCHAR(32) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_member_role_v2 UNIQUE (tenant_id, identity_user_id, role),
    CONSTRAINT ck_tenant_member_role_v2_role CHECK (
        role IN ('TENANT_ADMIN', 'SECURITY_ADMIN', 'KNOWLEDGE_ADMIN', 'AUDITOR', 'MEMBER')
    )
);

INSERT INTO tenant_member_role_v2 (tenant_id, identity_user_id, role)
SELECT u.tenant_id, iu.id,
       CASE upper(COALESCE(u.role, 'MEMBER'))
           WHEN 'ADMIN' THEN 'TENANT_ADMIN'
           WHEN 'TENANT_ADMIN' THEN 'TENANT_ADMIN'
           WHEN 'AUDITOR' THEN 'AUDITOR'
           ELSE 'MEMBER'
       END
FROM sys_user u
JOIN identity_user_v2 iu ON iu.legacy_user_id = u.id
ON CONFLICT (tenant_id, identity_user_id, role) DO NOTHING;

-- Immutable index profiles. All imported profiles require manual model verification.
CREATE TABLE IF NOT EXISTS index_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT NOT NULL REFERENCES sys_tenant(id),
    name                  VARCHAR(128) NOT NULL,
    profile_version       INTEGER NOT NULL,
    embedding_provider    VARCHAR(128) NOT NULL,
    embedding_model       VARCHAR(256) NOT NULL,
    model_revision        VARCHAR(256) NOT NULL,
    embedding_dimension   INTEGER NOT NULL,
    normalization         VARCHAR(16) NOT NULL DEFAULT 'L2',
    distance_metric       VARCHAR(16) NOT NULL DEFAULT 'COSINE',
    chunker_config        JSONB NOT NULL,
    analyzer_config       JSONB NOT NULL DEFAULT '{}'::jsonb,
    reranker_provider     VARCHAR(128),
    reranker_model        VARCHAR(256),
    status                VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    activated_at          TIMESTAMPTZ,
    retired_at            TIMESTAMPTZ,
    CONSTRAINT uq_index_profile_migration UNIQUE (tenant_id, name, profile_version),
    CONSTRAINT uq_index_profile_migration_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT ck_index_profile_migration_dimension CHECK (embedding_dimension BETWEEN 64 AND 65536),
    CONSTRAINT ck_index_profile_migration_normalization CHECK (normalization IN ('NONE', 'L2')),
    CONSTRAINT ck_index_profile_migration_metric CHECK (distance_metric IN ('COSINE', 'L2', 'INNER_PRODUCT')),
    CONSTRAINT ck_index_profile_migration_chunker CHECK (jsonb_typeof(chunker_config) = 'object'),
    CONSTRAINT ck_index_profile_migration_analyzer CHECK (jsonb_typeof(analyzer_config) = 'object'),
    CONSTRAINT ck_index_profile_migration_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED'))
);

INSERT INTO index_profile (
    tenant_id, name, profile_version, embedding_provider, embedding_model,
    model_revision, embedding_dimension, chunker_config, analyzer_config, status
)
SELECT k.tenant_id,
       'legacy-kb-' || k.id::text,
       1,
       'migration.unverified',
       COALESCE(NULLIF(k.embedding_model, ''), 'unknown'),
       'migration-unverified',
       1024,
       jsonb_build_object(
           'strategy', 'legacy-fixed',
           'maxTokens', k.chunk_size,
           'overlapTokens', k.chunk_overlap
       ),
       '{}'::jsonb,
       'DRAFT'
FROM kb k
ON CONFLICT (tenant_id, name, profile_version) DO NOTHING;

ALTER TABLE kb ADD COLUMN IF NOT EXISTS index_profile_id_v2 BIGINT;
UPDATE kb k
SET index_profile_id_v2 = p.id
FROM index_profile p
WHERE p.tenant_id = k.tenant_id
  AND p.name = 'legacy-kb-' || k.id::text
  AND p.profile_version = 1
  AND k.index_profile_id_v2 IS NULL;

-- Additive document governance columns. Names carry _v2 to avoid reinterpreting legacy status.
ALTER TABLE document ADD COLUMN IF NOT EXISTS lifecycle_status_v2 VARCHAR(24);
ALTER TABLE document ADD COLUMN IF NOT EXISTS authority_status_v2 VARCHAR(24);
ALTER TABLE document ADD COLUMN IF NOT EXISTS sensitivity_v2 VARCHAR(24);
ALTER TABLE document ADD COLUMN IF NOT EXISTS safety_status_v2 VARCHAR(24);
ALTER TABLE document ADD COLUMN IF NOT EXISTS retention_policy_id_v2 BIGINT;
ALTER TABLE document ADD COLUMN IF NOT EXISTS legal_hold_v2 BOOLEAN;
ALTER TABLE document ADD COLUMN IF NOT EXISTS row_version_v2 BIGINT;
-- Data region: kb 继承租户区域，document 可覆盖（C7 决策，见 04-数据库设计 §5）
ALTER TABLE kb ADD COLUMN IF NOT EXISTS data_region_v2 VARCHAR(64);
ALTER TABLE document ADD COLUMN IF NOT EXISTS data_region_v2 VARCHAR(64);

UPDATE document
SET lifecycle_status_v2 = COALESCE(lifecycle_status_v2, 'ACTIVE'),
    authority_status_v2 = COALESCE(
        authority_status_v2,
        CASE WHEN review_status = 'APPROVED' THEN 'PUBLISHED' ELSE 'DRAFT' END
    ),
    sensitivity_v2 = COALESCE(sensitivity_v2, 'INTERNAL'),
    safety_status_v2 = COALESCE(safety_status_v2, 'REQUIRES_RESCAN'),
    legal_hold_v2 = COALESCE(legal_hold_v2, false),
    row_version_v2 = COALESCE(row_version_v2, 0)
WHERE lifecycle_status_v2 IS NULL
   OR authority_status_v2 IS NULL
   OR sensitivity_v2 IS NULL
   OR safety_status_v2 IS NULL
   OR legal_hold_v2 IS NULL
   OR row_version_v2 IS NULL;

-- Reliable side-effect and request deduplication foundations.
CREATE TABLE IF NOT EXISTS idempotency_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT       NOT NULL REFERENCES sys_tenant(id),
    operation        VARCHAR(64)  NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_sha256   CHAR(64)     NOT NULL,
    status           VARCHAR(16)  NOT NULL DEFAULT 'PROCESSING',
    resource_type    VARCHAR(64),
    resource_id      VARCHAR(128),
    response_status  INTEGER,
    response_sha256  CHAR(64),
    expires_at       TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_idempotency_record_v2 UNIQUE (tenant_id, operation, idempotency_key),
    CONSTRAINT ck_idempotency_record_v2_request CHECK (request_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_record_v2_response CHECK (response_sha256 IS NULL OR response_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_record_v2_status CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_idempotency_record_v2_expiry CHECK (expires_at > created_at)
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL REFERENCES sys_tenant(id),
    event_id          UUID          NOT NULL DEFAULT gen_random_uuid(),
    aggregate_type    VARCHAR(64)   NOT NULL,
    aggregate_id      VARCHAR(128)  NOT NULL,
    aggregate_version BIGINT        NOT NULL,
    event_type        VARCHAR(128)  NOT NULL,
    topic             VARCHAR(32)   NOT NULL DEFAULT 'general',
    payload           JSONB         NOT NULL,
    status            VARCHAR(16)   NOT NULL DEFAULT 'NEW',
    attempt_count     INTEGER       NOT NULL DEFAULT 0,
    available_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    occurred_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    published_at      TIMESTAMPTZ,
    last_error_code   VARCHAR(64),
    dead_letter_at    TIMESTAMPTZ,
    CONSTRAINT uq_outbox_event_v2_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_outbox_event_v2_event_id UNIQUE (event_id),
    CONSTRAINT uq_outbox_event_v2_aggregate UNIQUE (
        tenant_id, aggregate_type, aggregate_id, aggregate_version, event_type
    ),
    CONSTRAINT ck_outbox_event_v2_version CHECK (aggregate_version >= 1),
    CONSTRAINT ck_outbox_event_v2_payload CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_outbox_event_v2_status CHECK (status IN ('NEW', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD')),
    CONSTRAINT ck_outbox_event_v2_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_outbox_event_v2_topic CHECK (topic IN (
        'sync', 'ingestion', 'index', 'webhook', 'governance', 'general'
    ))
);
CREATE INDEX IF NOT EXISTS idx_outbox_event_v2_dispatch
    ON outbox_event (status, available_at, id) WHERE status IN ('NEW', 'FAILED');
CREATE INDEX IF NOT EXISTS idx_outbox_event_v2_claim
    ON outbox_event (topic, status, available_at) WHERE status IN ('NEW', 'FAILED');

-- Deletion task/target/receipt records make cross-store disposition auditable.
CREATE TABLE IF NOT EXISTS deletion_task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT        NOT NULL REFERENCES sys_tenant(id),
    resource_type       VARCHAR(24)   NOT NULL,
    resource_id         VARCHAR(256)  NOT NULL,
    reason              VARCHAR(2048) NOT NULL,
    requested_by        BIGINT,
    idempotency_key     VARCHAR(128)  NOT NULL,
    status              VARCHAR(16)   NOT NULL DEFAULT 'QUEUED',
    preview_json        JSONB         NOT NULL DEFAULT '{}'::jsonb,
    legal_hold_blocked  BOOLEAN       NOT NULL DEFAULT FALSE,
    blocked_reason_code VARCHAR(64),
    target_count        INTEGER       NOT NULL DEFAULT 0,
    completed_count     INTEGER       NOT NULL DEFAULT 0,
    failed_count        INTEGER       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    CONSTRAINT uq_deletion_task_v2_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_deletion_task_v2_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT ck_deletion_task_v2_resource CHECK (resource_type IN ('TENANT', 'KB', 'DOCUMENT', 'VERSION')),
    CONSTRAINT ck_deletion_task_v2_status CHECK (status IN ('QUEUED', 'RUNNING', 'BLOCKED', 'PARTIAL', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_deletion_task_v2_preview CHECK (jsonb_typeof(preview_json) = 'object'),
    CONSTRAINT ck_deletion_task_v2_counts CHECK (
        target_count >= 0 AND completed_count >= 0 AND failed_count >= 0
        AND completed_count + failed_count <= target_count
    ),
    CONSTRAINT ck_deletion_task_v2_blocked CHECK (
        (status = 'BLOCKED' AND blocked_reason_code IS NOT NULL)
        OR status <> 'BLOCKED'
    )
);
CREATE INDEX IF NOT EXISTS idx_deletion_task_v2_queue
    ON deletion_task (tenant_id, status, created_at)
    WHERE status IN ('QUEUED', 'RUNNING', 'PARTIAL', 'FAILED');

CREATE TABLE IF NOT EXISTS deletion_target (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT        NOT NULL REFERENCES sys_tenant(id),
    deletion_task_id   BIGINT        NOT NULL,
    target_type        VARCHAR(24)   NOT NULL,
    target_key         VARCHAR(1024) NOT NULL,
    status             VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    expected_count     BIGINT        NOT NULL DEFAULT 1,
    deleted_count      BIGINT        NOT NULL DEFAULT 0,
    result_sha256      CHAR(64),
    backup_expires_at  TIMESTAMPTZ,
    last_error_code    VARCHAR(64),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    completed_at       TIMESTAMPTZ,
    CONSTRAINT fk_deletion_target_v2_task
        FOREIGN KEY (tenant_id, deletion_task_id)
        REFERENCES deletion_task (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_deletion_target_v2 UNIQUE (tenant_id, deletion_task_id, target_type, target_key),
    CONSTRAINT ck_deletion_target_v2_type CHECK (
        target_type IN ('OBJECT', 'CHUNK_META', 'SEARCH_INDEX', 'CACHE', 'PREVIEW', 'SOURCE_LINK', 'BACKUP_EXCEPTION')
    ),
    CONSTRAINT ck_deletion_target_v2_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', 'RETAINED')),
    CONSTRAINT ck_deletion_target_v2_counts CHECK (expected_count >= 0 AND deleted_count >= 0 AND deleted_count <= expected_count),
    CONSTRAINT ck_deletion_target_v2_sha CHECK (result_sha256 IS NULL OR result_sha256 ~ '^[0-9a-f]{64}$')
);
CREATE INDEX IF NOT EXISTS idx_deletion_target_v2_queue
    ON deletion_target (tenant_id, status, updated_at)
    WHERE status IN ('PENDING', 'RUNNING', 'FAILED');

CREATE TABLE IF NOT EXISTS deletion_receipt (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL REFERENCES sys_tenant(id),
    deletion_task_id   BIGINT       NOT NULL,
    result             VARCHAR(16)  NOT NULL,
    summary_json       JSONB        NOT NULL,
    receipt_sha256     CHAR(64)     NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_deletion_receipt_v2_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_deletion_receipt_v2_task UNIQUE (tenant_id, deletion_task_id),
    CONSTRAINT fk_deletion_receipt_v2_task
        FOREIGN KEY (tenant_id, deletion_task_id)
        REFERENCES deletion_task (tenant_id, id),
    CONSTRAINT ck_deletion_receipt_v2_result CHECK (result IN ('SUCCEEDED', 'PARTIAL', 'BLOCKED')),
    CONSTRAINT ck_deletion_receipt_v2_summary CHECK (jsonb_typeof(summary_json) = 'object'),
    CONSTRAINT ck_deletion_receipt_v2_sha CHECK (receipt_sha256 ~ '^[0-9a-f]{64}$')
);

INSERT INTO schema_migration (version, phase, notes)
VALUES (
    '0.2-enterprise-generalization',
    'EXPAND',
    'Additive structures only; application dual-write, reconciliation, index rebuild and contract phase remain required.'
)
ON CONFLICT (version) DO UPDATE
SET applied_at = now(), applied_by = current_user, notes = EXCLUDED.notes;

COMMIT;

\echo 'v0.2 EXPAND completed. Do not cut over until dual-write reconciliation and index quality gates pass.'

\else

\echo 'Skipped: legacy v0.1 signature not found (or v0.2/newer schema already present).'

\endif
